#Variables

@baseUrl = http://localhost:3333

#Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

#Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms


###

#Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de Teste",
  "description": "Esta é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

#Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

#Create question
# @name createQuestion
POST {{baseUrl}}/rooms/1cd4e675-c196-4364-89f1-4ff1b0e25832/questions
Content-Type: application/json

{
  "question": "O que é uma batata?"
}



